### ISSUE TITLE
Question: Dynamic plugin location

### ISSUE THREAD

**Issue by cdimitroulas** [samhh/typescript-tshm-plugin#2]
Hi there,

More of a question than an issue so sorry about that. As an `nvm` user, the location of the typescript-tshm-plugin node_module will depend on which version of node I'm currently using so I'd like to be able to dynamically set this depending on the node version in use when neovim is launched. Do you know how to achieve this?

Currently I've harded coded the location to " /home/<my_user>/.nvm/versions/node/v16.5.0/lib/node_modules/typescript-tshm-plugin/" but obviously this won't work after changing node version :D

**Comment by samhh** [comment]
In my case with Arch I'm using the global Node/npm installation for stuff like this. With fnm/nvm/etc you just need to install via "system" Node so that it's installed to a fixed location that transcends the prefixes.

**Comment by cdimitroulas** [comment]
Thanks for your response
